# Generated by Django 3.0.4 on 2020-04-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Groups',
            fields=[
                ('group_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
