# Generated by Django 3.0.4 on 2020-04-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_group', '0003_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
