# Generated by Django 2.1.5 on 2020-04-19 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_group', '0004_auto_20200412_1033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_date']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='Dead_line',
        ),
        migrations.AlterField(
            model_name='task',
            name='Catagories',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Task', to='task_group.Catagories'),
        ),
    ]
