# Generated by Django 2.1.5 on 2020-04-19 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_group', '0005_auto_20200419_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='done',
        ),
    ]
